language: ruby
rvm:
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
install: 
 - gem install selenium-webdriver
 - gem install rspec 

script: rake test 
